import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';

// importing bootstrap
import './../node_modules/bootstrap/dist/css/bootstrap.min.css';

 

import UseReducerComponent from './hooks/reducerhook';

import reportWebVitals from './reportWebVitals';

 //let message = 'Hi Component you are being mounted';
// let newmessage  = "New Message";

// Mount the App component on the HTML element having 'id' as 'root'
// msg is the custom JSX attribute that will be generated by React.js JSX parser
// at runtime and the property 'message' will be passed to <FirstComponent/>
// the FirstComponent must accept it as the 'props'
// BrowserRouter: will execute the Default Link i.e. <Link to="/">
ReactDOM.render(
  <React.StrictMode>
     <UseReducerComponent></UseReducerComponent>
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
